/* generated by jz */

package com.jzs.utils;


/**
*  
* com.jzs.utils.ConfigOption 
*
* {@hide} 
*/
public final class ConfigOption
{
    /**
     * check if ENABLE_JZS_JARS is turned on or not
     */
    public static final boolean ENABLE_JZS_JARS = true;
    /**
     * check if ENABLE_JZS_POLICY is turned on or not
     */
    public static final boolean ENABLE_JZS_POLICY = true;
    /**
     * check if JZS_ENABLE_CUSTOM_APPS is turned on or not
     */
    public static final boolean JZS_ENABLE_CUSTOM_APPS = true;
    /**
     * check if QS_SUPPORT_LOCKSCREEN_WALLPAPER is turned on or not
     */
    public static final boolean QS_SUPPORT_LOCKSCREEN_WALLPAPER = true;
    /**
     * check if QS_SUPPORT_NAVIGATIONBAR is turned on or not
     */
    public static final boolean QS_SUPPORT_NAVIGATIONBAR = false;
    /**
     * check if QS_SUPPORT_APK_TO_PHONE_STORAGE is turned on or not
     */
    public static final boolean QS_SUPPORT_APK_TO_PHONE_STORAGE = false;
    /**
     * check if QS_SUPPORT_USB_OTG is turned on or not
     */
    public static final boolean QS_SUPPORT_USB_OTG = true;
    /**
     * check if QS_SUPPORT_SS_CALLLOG_SLIDE is turned on or not
     */
    public static final boolean QS_SUPPORT_SS_CALLLOG_SLIDE = false;
    /**
     * check if QS_SUPPORT_SS_CALLPAD_WIDGET is turned on or not
     */
    public static final boolean QS_SUPPORT_SS_CALLPAD_WIDGET = false;
    /**
     * check if QS_ENABLE_TURNING_SILENT is turned on or not
     */
    public static final boolean QS_ENABLE_TURNING_SILENT = false;
    /**
     * check if QS_SUPPORT_CUSTOM_HDMI is turned on or not
     */
    public static final boolean QS_SUPPORT_CUSTOM_HDMI = false;
    /**
     * check if QS_ENABLE_GOOGLE_FACELOCK is turned on or not
     */
    public static final boolean QS_ENABLE_GOOGLE_FACELOCK = false;
    /**
     * check if QS_ENABLE_IHD_EXT_STYLE is turned on or not
     */
    public static final boolean QS_ENABLE_IHD_EXT_STYLE = false;
    /**
     * check if QS_DISABLE_STATUS_BAR_TOOLBAR is turned on or not
     */
    public static final boolean QS_DISABLE_STATUS_BAR_TOOLBAR = false;
    /**
     * check if QS_SUPPORT_TOUCH_PEN is turned on or not
     */
    public static final boolean QS_SUPPORT_TOUCH_PEN = false;
    /**
     * check if QS_ENABLE_SHOT_BY_POWER_HOME_KEY is turned on or not
     */
    public static final boolean QS_ENABLE_SHOT_BY_POWER_HOME_KEY = true;
    /**
     * check if QS_GESTURE_CHANGE is turned on or not
     */
    public static final boolean QS_GESTURE_CHANGE = false;
    /**
     * check if QS_SUPPORT_SDCARD2 is turned on or not
     */
    public static final boolean QS_SUPPORT_SDCARD2 = true;
    /**
     * check if QS_SUPPORT_COVER is turned on or not
     */
    public static final boolean QS_SUPPORT_COVER = true;
    /**
     * check if QS_THEME_MANAGER_APP is turned on or not
     */
    public static final boolean QS_THEME_MANAGER_APP = false;
    /**
     * check if QS_SUPPORT_FLOAT_SHORTCUT_KEY is turned on or not
     */
    public static final boolean QS_SUPPORT_FLOAT_SHORTCUT_KEY = false;
    /**
     * check if QS_SUPPORT_RGB_LED_LIGHTS is turned on or not
     */
    public static final boolean QS_SUPPORT_RGB_LED_LIGHTS = false;
    /**
     * check if QS_TPD_SUPPORT_GESTURE is turned on or not
     */
    public static final boolean QS_TPD_SUPPORT_GESTURE = false;
    /**
     * check if QS_S3D_SUPPORT is turned on or not
     */
    public static final boolean QS_S3D_SUPPORT = false;
    /**
     * check if QS_SD_EXT4_SUPPORT is turned on or not
     */
    public static final boolean QS_SD_EXT4_SUPPORT = false;
    /**
     * check if QS_DOUBLE_KEY_EXCHANGE_VALUE is turned on or not
     */
    public static final int QS_DOUBLE_KEY_EXCHANGE_VALUE = 0;
    /**
     * check if QS_ENABLE_DOUBLE_KEY_FUNC is turned on or not
     */
    public static final int QS_ENABLE_DOUBLE_KEY_FUNC = 0;
    /**
     * check if QS_DEFAULT_LCD_ORIENTATION_ANGLE is turned on or not
     */
    public static final int QS_DEFAULT_LCD_ORIENTATION_ANGLE = 0;
    /**
     * check if QS_PHONE_NUMBER_MATCH_LENGTH is turned on or not
     */
    public static final int QS_PHONE_NUMBER_MATCH_LENGTH = 0;
    /**
     * check if QS_DEFAULT_FRAMEWORK_STYLE is turned on or not
     */
    public static final int QS_DEFAULT_FRAMEWORK_STYLE = 1;
    /**
     * check if QS_SUPPORT_LED_LIGHTS is turned on or not
     */
    public static final int QS_SUPPORT_LED_LIGHTS = 0;
    /**
     * check if QS_FONT_SCALE_PERCENT is turned on or not
     */
    public static final int QS_FONT_SCALE_PERCENT = 0;
    /**
     * check if JZS_GLOBAL_FRAMEWORK_VERSION is turned on or not
     */
    public static final int JZS_GLOBAL_FRAMEWORK_VERSION = 2;
    /**
     * check if QS_DEFAULT_LAUNCHER is turned on or not
     */
    public static final String QS_DEFAULT_LAUNCHER = "";
    /**
     * check if QS_DEFAULT_VIDEO_WALLPAPER is turned on or not
     */
    public static final String QS_DEFAULT_VIDEO_WALLPAPER = "";
    /**
     * check if QS_FAKE_HARDWARE_TEST_PRJ is turned on or not
     */
    public static final String QS_FAKE_HARDWARE_TEST_PRJ = "";
    /**
     * check if QS_ENABLE_IME_LIST is turned on or not
     */
    public static final String QS_ENABLE_IME_LIST = "";
    public static final String QS_PRJ_NAME = "A820_WW_52";
    public static final boolean QS_THEME_ANDROID = true;
    public static final boolean QS_THEME_SAMSUNG = false;
    public static final boolean QS_THEME_IPHONE = false;
    public static final boolean QS_THEME_HTC = false;
    public static final boolean QS_THEME_QISHANG = false;
    public static final boolean QS_THEME_WPHONE = false;
    public static final boolean QS_THEME_XIAOMI = false;
    public static final boolean QS_THEME_MEIZU = false;
    public static final boolean QS_THEME_LAOREN = false;
    public static final boolean QS_THEME_SUPPORT = false;


    public static final int QS_ENABLE_BACK_LONGPRESS_FUNC = 0;
    public static final int QS_ENABLE_MENU_KEY_LONGPRESS_FUNC = 0;
    public static final int QS_FAKE_DISPLAY_WIDTH_SIZE = 0;
    public static final int QS_FAKE_DISPLAY_HEIGHT_SIZE = 0;
    
 
}
